import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { ticker, analysis, quote } = body;

    const pdfContent = `
INVESTMENT RESEARCH REPORT
${ticker}
Generated: ${new Date().toLocaleDateString()}
=====================================

PRICE SUMMARY
Price: $${quote?.price || "N/A"}
Change: $${quote?.change || "N/A"} (${quote?.changePercent || "N/A"}%)
Open: $${quote?.open || "N/A"}
High: $${quote?.high || "N/A"}
Low: $${quote?.low || "N/A"}

AI ANALYSIS
Confidence Score: ${analysis?.confidenceScore || "N/A"}%
Sentiment: ${analysis?.sentiment || "N/A"}
Risk Level: ${analysis?.riskLevel || "N/A"}

Summary:
${analysis?.summary || "N/A"}

BULL CASE:
${analysis?.bullCase?.map((b: string, i: number) => `${i + 1}. ${b}`).join("\n") || "N/A"}

BEAR CASE:
${analysis?.bearCase?.map((b: string, i: number) => `${i + 1}. ${b}`).join("\n") || "N/A"}

Key Catalyst: ${analysis?.keyCatalyst || "N/A"}
Price Target: $${analysis?.priceTarget || "N/A"}
Technical Signal: ${analysis?.technicalSignal || "N/A"}
Volatility Note: ${analysis?.volatilityNote || "N/A"}
=====================================
DISCLAIMER: This report is generated by AI and is for informational purposes only.
    `.trim();

    return new NextResponse(pdfContent, {
      headers: {
        "Content-Type": "text/plain",
        "Content-Disposition": `attachment; filename="${ticker}_research_report.txt"`,
      },
    });
  } catch (error) {
    console.error("Export API error:", error);
    return NextResponse.json(
      { error: "Failed to export report" },
      { status: 500 }
    );
  }
}
